ALTER TABLE tasks ADD COLUMN summary TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN terminal_reason TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN artifacts_json TEXT NOT NULL DEFAULT '[]';

ALTER TABLE runs ADD COLUMN terminal_reason TEXT NOT NULL DEFAULT '';
ALTER TABLE runs ADD COLUMN artifacts_json TEXT NOT NULL DEFAULT '[]';
