ALTER TABLE tasks ADD COLUMN workspace_id INTEGER REFERENCES workspaces(id) ON DELETE SET NULL;
ALTER TABLE tasks ADD COLUMN initiative_id INTEGER REFERENCES initiatives(id) ON DELETE SET NULL;
ALTER TABLE tasks ADD COLUMN companion_id INTEGER REFERENCES companions(id) ON DELETE SET NULL;
ALTER TABLE tasks ADD COLUMN work_kind TEXT;
