package knowledge

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

type manifestFrontmatter struct {
	Kind           string   `yaml:"kind"`
	Key            string   `yaml:"key"`
	Title          string   `yaml:"title"`
	Scope          string   `yaml:"scope"`
	ScopeKey       string   `yaml:"scope_key"`
	Restricted     bool     `yaml:"restricted"`
	SourceKind     string   `yaml:"source_kind"`
	SourceClass    string   `yaml:"source_class"`
	ArtifactSHA256 string   `yaml:"artifact_sha256"`
	ArtifactRef    string   `yaml:"artifact_ref"`
	OriginalPath   string   `yaml:"original_path"`
	RefreshPolicy  string   `yaml:"refresh_policy"`
	Extractor      string   `yaml:"extractor"`
	CitationPolicy string   `yaml:"citation_policy"`
	Topics         []string `yaml:"topics"`
	Entities       []string `yaml:"entities"`
	RelatedSources []string `yaml:"related_sources"`
	AppliesTo      []string `yaml:"applies_to"`
}

func (s Service) writeManifest(params IngestParams, artifact artifactRecord, extraction extractionResult) (string, error) {
	repoRoot, err := cleanAbsPath(s.RepoRoot, "repo root")
	if err != nil {
		return "", err
	}
	manifestPath := canonicalManifestPath(params.Key)
	fullPath := filepath.Join(repoRoot, filepath.FromSlash(manifestPath))
	if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
		return "", err
	}

	frontmatter := manifestFrontmatter{
		Kind:           "knowledge_source",
		Key:            params.Key,
		Title:          params.Title,
		Scope:          params.Scope,
		ScopeKey:       params.ScopeKey,
		Restricted:     params.Restricted,
		SourceKind:     params.SourceKind,
		SourceClass:    string(params.SourceClass),
		ArtifactSHA256: artifact.SHA256,
		ArtifactRef:    artifact.ArtifactRef,
		OriginalPath:   artifact.OriginalPath,
		RefreshPolicy:  valueOrDefault(params.RefreshPolicy, DefaultRefreshPolicy),
		Extractor:      extraction.Extractor(),
		CitationPolicy: valueOrDefault(params.CitationPolicy, DefaultCitationPolicy),
		Topics:         emptySlice(params.Topics),
		Entities:       emptySlice(params.Entities),
		RelatedSources: emptySlice(params.RelatedSources),
		AppliesTo:      emptySlice(params.AppliesTo),
	}
	yamlBytes, err := yaml.Marshal(frontmatter)
	if err != nil {
		return "", err
	}

	body := fmt.Sprintf("---\n%s---\n\n# %s\n\nGenerated by Odin Knowledge Source ingestion. Source bytes are stored as a content-addressed Knowledge Artifact.\n", string(yamlBytes), params.Title)
	if err := os.WriteFile(fullPath, []byte(body), 0o644); err != nil {
		return "", err
	}
	return manifestPath, nil
}

func canonicalManifestPath(key string) string {
	return "memory/knowledge/" + key + ".md"
}

func emptySlice(values []string) []string {
	if values == nil {
		return []string{}
	}
	return values
}

func valueOrDefault(value string, fallback string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return fallback
	}
	return value
}
