#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
script="${repo_root}/scripts/ops/homelab-release-dry-run.sh"
runbook="${repo_root}/docs/operations/homelab-odin-runbook.md"
proxy_config="${repo_root}/deploy/nginx/odin-pwa-proxy.conf"
overseer_launcher="${repo_root}/deploy/docker/run-odin-overseer-host.sh"
env_example="${repo_root}/deploy/systemd/odin-os.env.example"
makefile="${repo_root}/Makefile"

fail() {
  echo "homelab-release-dry-run-test: $*" >&2
  exit 1
}

[[ -x "${script}" ]] || fail "dry-run script must be executable"
[[ -f "${runbook}" ]] || fail "homelab runbook must exist"
[[ -f "${proxy_config}" ]] || fail "repo-owned PWA proxy config must exist"
[[ -x "${overseer_launcher}" ]] || fail "repo-owned odin-overseer launcher must be executable"
[[ -f "${env_example}" ]] || fail "env example must exist"

grep -Fq "scripts/install-service.sh --dry-run --start" "${script}" || fail "script must prove service install dry-run"
grep -Fq "./bin/odin backup --help" "${script}" || fail "script must check backup help"
grep -Fq "./bin/odin restore --help" "${script}" || fail "script must check restore help"
grep -Fq "./bin/odin verify-backup --help" "${script}" || fail "script must check verify-backup help"
grep -Fq "./bin/odin serve --help" "${script}" || fail "script must check serve help"
grep -Fq "deploy/docker/run-odin-overseer-host.sh" "${script}" || fail "script must require repo-owned odin-overseer launcher"
grep -Fq "./bin/odin doctor --json" "${script}" || fail "script must gate on doctor"
grep -Fq "./bin/odin healthcheck" "${script}" || fail "script must gate on healthcheck"
grep -Fq "./bin/odin overview --json" "${script}" || fail "script must gate on overview"
grep -Fq "./bin/odin work status --json" "${script}" || fail "script must gate on work status"
grep -Fq "./bin/odin review list --json" "${script}" || fail "script must gate on review queue"
grep -Fq "./bin/odin approvals all --json" "${script}" || fail "script must gate on approvals"
grep -Fq "make odin-actual-use-e2e" "${runbook}" || fail "runbook must include actual-use e2e gate"
grep -Fq "verify-backup" "${runbook}" || fail "runbook must require backup verification"
grep -Fq "rollback" "${runbook}" || fail "runbook must document rollback"
grep -Fq "homelab-release-dry-run" "${makefile}" || fail "Makefile must expose dry-run target"
grep -Fq "odin-actual-use-e2e" "${makefile}" || fail "Makefile must expose actual-use target"
grep -Fq "location = /browser/session/handoff" "${proxy_config}" || fail "proxy config must allow exact browser handoff route"
grep -Fq "location = /browser/session/handoff/viewer" "${proxy_config}" || fail "proxy config must allow exact protected viewer route"
grep -Fq "location /browser/session/handoff/viewer/proxy/" "${proxy_config}" || fail "proxy config must allow protected viewer proxy route"
grep -Fq "location = /browser/session/handoff/complete" "${proxy_config}" || fail "proxy config must allow exact browser handoff completion route"
grep -Fq "error_page 403 =404 /__not_found" "${proxy_config}" || fail "proxy config must mask denied routes as not found"
grep -Fq "location = /metrics" "${proxy_config}" || fail "proxy config must expose exact private metrics route"
grep -Fq "allow 192.168.96.0/20" "${proxy_config}" || fail "private metrics route must stay tailnet-scoped"
grep -Fq "deny all" "${proxy_config}" || fail "private metrics route must deny untrusted clients"
grep -Fq "location = /webhooks/n8n/intake" "${proxy_config}" || fail "proxy config must allow exact n8n intake webhook route"
grep -Eq 'location[[:space:]]+/api/[[:space:]]*\{' "${proxy_config}" && fail "proxy config must not expose broad api paths"
grep -Eq 'location[[:space:]]+/browser/[[:space:]]*\{' "${proxy_config}" && fail "proxy config must not expose broad browser paths"
grep -Eq 'location[[:space:]]+/webhooks/[[:space:]]*\{' "${proxy_config}" && fail "proxy config must not expose broad webhook paths"
grep -Fq "/browser/session/handoff" "${runbook}" || fail "runbook must document browser handoff route proof"
grep -Fq "deploy/docker/run-odin-overseer-host.sh" "${runbook}" || fail "runbook must document repo-owned odin-overseer launcher"
grep -Fq "ODIN_NOVNC_PRIVATE_BASE_URL" "${env_example}" || fail "env example must document noVNC private base URL"
grep -Fq "ODIN_BROWSER_PROFILE_KEY_B64" "${env_example}" || fail "env example must document encrypted browser profile key"
grep -Fq "ODIN_BROWSER_PROOF_TITLE_COMMAND" "${env_example}" || fail "env example must document saved-session proof title command"
grep -Fq "ODIN_BROWSER_PROOF_TITLE_ALLOWED_COMMANDS" "${env_example}" || fail "env example must document saved-session proof title allowlist"
grep -Fq 'ODIN_OVERSEER_NETWORK:-infrastructure_default' "${overseer_launcher}" || fail "overseer launcher must default to the live infrastructure network"
grep -Fq 'ODIN_OVERSEER_NGINX_CONFIG:-$release_link/deploy/nginx/odin-pwa-proxy.conf' "${overseer_launcher}" || fail "overseer launcher must default nginx config to the release"
grep -Fq 'ODIN_OVERSEER_MONITORING_NETWORK:-odin-monitoring_default' "${overseer_launcher}" || fail "overseer launcher must default to the live monitoring network"
grep -Fq 'ODIN_OVERSEER_USER:-0:0' "${overseer_launcher}" || fail "overseer launcher must default to the live proven container user"
grep -Fq 'ODIN_OVERSEER_MEMORY:-8g' "${overseer_launcher}" || fail "overseer launcher must carry live memory limit"
grep -Fq 'ODIN_OVERSEER_MEMORY_SWAP:-9g' "${overseer_launcher}" || fail "overseer launcher must carry live memory-swap limit"
grep -Fq 'ODIN_OVERSEER_GOMEMLIMIT:-6144MiB' "${overseer_launcher}" || fail "overseer launcher must carry live Go memory limit"
grep -Fq 'ODIN_OVERSEER_GOGC:-100' "${overseer_launcher}" || fail "overseer launcher must carry live Go GC setting"
grep -Fq 'ODIN_PROJECTS_OVERLAY:-$HOME/.config/odin/odin-os-projects.local.yaml' "${overseer_launcher}" || fail "overseer launcher must carry live project overlay default"
grep -Fq 'ODIN_CODEX_DRIVER:-$HOME/.config/odin/odin-codex-live-driver.sh' "${overseer_launcher}" || fail "overseer launcher must carry live Codex driver default"
grep -Fq 'ODIN_BROWSER_HANDOFF_BASE_URL:-https://odin.marcusgoll.com/browser/session/handoff' "${overseer_launcher}" || fail "overseer launcher must carry protected handoff base URL"
grep -Fq 'ODIN_FAMILY_OPS_CUTOVER_WORKTREE:-$HOME/.config/superpowers/worktrees/family-ops/odin-os-cutover-main' "${overseer_launcher}" || fail "overseer launcher must carry live family-ops cutover worktree default"
grep -Fq -- "--network host" "${overseer_launcher}" || fail "overseer launcher must retain optional host network mode"
grep -Fq -- "--cap-add NET_BIND_SERVICE" "${overseer_launcher}" || fail "overseer launcher must grant low-port bind capability only in host mode"
grep -Fq "docker network connect --alias" "${overseer_launcher}" || fail "overseer launcher must attach monitoring network when bridged"
grep -Fq "PYTHONPATH" "${overseer_launcher}" || fail "overseer launcher must expose websockify python package path"
grep -Fq "/opt/google/chrome:/opt/google/chrome:ro" "${overseer_launcher}" || fail "overseer launcher must mount Chrome runtime"
grep -Fq 'ODIN_FAMILY_OPS_CUTOVER_WORKTREE' "${overseer_launcher}" || fail "overseer launcher must mount the Family Ops cutover worktree"
grep -Fq "/var/odin/browser-state/novnc-root:/var/odin/browser-state/novnc-root:ro" "${overseer_launcher}" || fail "overseer launcher must mount noVNC web assets"
grep -Fq "/usr/bin/Xvfb:/usr/bin/Xvfb:ro" "${overseer_launcher}" || fail "overseer launcher must mount Xvfb"
grep -Fq "/usr/bin/x11vnc:/usr/bin/x11vnc:ro" "${overseer_launcher}" || fail "overseer launcher must mount x11vnc"
grep -Fq "/usr/bin/xwininfo:/usr/bin/xwininfo:ro" "${overseer_launcher}" || fail "overseer launcher must mount xwininfo for proof"
grep -Fq "/usr/lib/python3.12:/usr/lib/python3.12:ro" "${overseer_launcher}" || fail "overseer launcher must mount python stdlib"
grep -Fq '$family_ops_worktree:$family_ops_worktree:ro' "${overseer_launcher}" || fail "overseer launcher must mount family-ops cutover worktree"
grep -Fq "browser session prove" "${repo_root}/docs/operations/browser-handoff-runner.md" || fail "browser handoff runbook must document saved-profile proof command"

echo "ok"
